import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div><Header /></div>
        <div>{children}</div>
      </body>
    </html>
  );
}
